services:
  - type: web
    name: shopcontentvn-ai
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_VISION_MODEL
        value: gpt-4.1-mini
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
